;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        evil-backward-char
        evil-backward-word-begin
        evil-forward-char
        evil-forward-word-end
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-substitute
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        ))
